import builtins from 'builtin-modules';
import dotenv from 'dotenv';
import esbuild from 'esbuild';
import process from 'process';
import { createDevVaultPlugin } from './scripts/build/create-dev-vault-plugin.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Load .env file
dotenv.config();

const DEV_VAULT_PLUGIN_FOLDER = process.env.DEV_VAULT_PLUGIN_FOLDER;
const prod = process.argv[2] === 'production';

if (!prod && !DEV_VAULT_PLUGIN_FOLDER) {
  console.error('Error: DEV_VAULT_PLUGIN_FOLDER is not defined in .env');
  process.exit(1);
}

const plugins = [];

if (!prod) {
  plugins.push(createDevVaultPlugin(DEV_VAULT_PLUGIN_FOLDER));
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  plugins,
});

if (prod) {
  try {
    await context.rebuild();
  } finally {
    await context.dispose();
  }
} else {
  await context.watch();
}
